FROM golang:latest AS builder

WORKDIR /usr/src/app

COPY . .

RUN go mod tidy
RUN go build -o main

# Otimizando imagem - Multistagin build
FROM scratch

COPY --from=builder /usr/src/app/main .

CMD [ "./main" ]
